Feature/neo 623 map serializer as arrays
BraintagsGmbH/vertx-util pull request #37
Opened 2017-07-18 11:41 UTC by mpluecker

2017-07-21 13:29 UTC, sschmittBt requested changes

2017-07-21 13:29 UTC, sschmittBt commented on src/main/java/de/braintags/vertx/util/json/ArrayMapNode.java
> +      }
Can be replaced by "isArrayMapNode"

2017-07-21 13:29 UTC, sschmittBt commented on src/main/java/de/braintags/vertx/util/json/ArrayMapNode.java
> +    innserSerialize(g, provider);
typo, "inner"

2017-07-21 13:29 UTC, sschmittBt commented on src/main/java/de/braintags/vertx/util/json/ArrayMapNode.java
> +    boolean trimEmptyArray = (provider != null) &&
What do you need this boolean for?

2017-07-21 13:29 UTC, sschmittBt commented on src/main/java/de/braintags/vertx/util/json/JsonDiff.java
> +        return arrayMapDiff((ArrayMapNode) base, (ArrayMapNode) data, nodeFactory, arrayMapsConverted);
How can you assume that every POJO node is already an ArrayMapNode?

2017-07-21 13:29 UTC, sschmittBt commented on src/main/java/de/braintags/vertx/util/json/deserializers/ArrayMapDeserializer.java
> +                wrapAndThrow(e, result, key.toString());
key might be null if value came before the key

2017-07-21 13:29 UTC, sschmittBt commented on src/test/java/de/braintags/vertx/util/json/TArrayMap.java
> +public class TArrayMap {
What about array maps in array maps? Or is it unsupported?

2017-07-24 09:13 UTC, mpluecker commented on src/main/java/de/braintags/vertx/util/json/ArrayMapNode.java
> +      }
this is intended, using "isArrayMapNode" would be slower

2017-07-24 09:14 UTC, mpluecker commented on src/main/java/de/braintags/vertx/util/json/ArrayMapNode.java
> +    boolean trimEmptyArray = (provider != null) &&
nothing ..

2017-07-24 09:14 UTC, mpluecker commented on src/main/java/de/braintags/vertx/util/json/ArrayMapNode.java
> +    innserSerialize(g, provider);
done

2017-07-24 10:28 UTC, mpluecker commented on src/test/java/de/braintags/vertx/util/json/TArrayMap.java
> +public class TArrayMap {
added support and test for that

2017-07-24 10:28 UTC, mpluecker commented on src/main/java/de/braintags/vertx/util/json/deserializers/ArrayMapDeserializer.java
> +                wrapAndThrow(e, result, key.toString());
done

2017-07-24 11:07 UTC, sschmittBt approved these changes

2017-07-24 11:07 UTC, merged