fix error writing null bytes
BraintagsGmbH/vertx-util pull request #84
Opened 2018-03-22 16:28 UTC by remi128

fix error null bytes; setting some vars protected

2018-03-22 17:05 UTC, sschmittBt requested changes

2018-03-22 17:05 UTC, sschmittBt commented on src/main/java/de/braintags/vertx/util/file/JsonReadStream.java
> +  protected final AtomicBoolean firstElementWritten = new AtomicBoolean(false);
Warum müssen die protected sein wenn die eh nur beim initialiseren gesetzt werden? Reicht es nicht, wenn du die überschreiben willst, den Constructor einfach zu überschreiben?

2018-03-22 17:52 UTC, remi128 commented on src/main/java/de/braintags/vertx/util/file/JsonReadStream.java
> +  protected final AtomicBoolean firstElementWritten = new AtomicBoolean(false);
sollen gelesen werden. Habs auf getter gebracht

2018-03-23 08:36 UTC, sschmittBt approved these changes

2018-03-23 08:36 UTC, merged